### ISSUE TITLE
unstake Failure Error

### ISSUE THREAD

**Issue by binghaiyi** [celo-org/staked-celo-web-app#250] opened 2024-05-25 00:09 UTC
### Package

Unstake

### What wallet app are you using to connect?

metamask

### Browser

Chrome

### Describe the bug

The contract function "withdraw" reverted with the following signature: 0x0d438664 Unable to decode signature "0x0d438664" as it was not found on the provided ABI. Make sure you are using the correct ABI and that the error exists on it. You can look up the decoded signature here: https://openchain.xyz/signatures?query=0x0d438664. Contract Call: address: 0x0239b96D10a434a56CC9E09383077A0490cF9398 function: withdraw(uint256 stCeloAmount) args: (1441273600000000000000) sender: 0xce22f4b16d95127883d6A58Ff91DD71Ceba50Ad7 Docs: https://viem.sh/docs/contract/decodeErrorResult.html Version: viem
![IMG_1351](https://github.com/celo-org/staked-celo-web-app/assets/170776059/96a58b8e-5291-4bf6-976f-eb30acd3ef13)

**Comment by nicolasbrugneaux** [comment] 2024-07-15 12:11
Hey @binghaiyi could you let us know if you still have the issue? We published a couple changes last week.

**Comment by soloseng** [comment] 2024-07-19 16:28
Closing as duplicate of https://github.com/celo-org/staked-celo/issues/203

**Closed by soloseng** 2024-07-19 16:28 UTC
